// Cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const CLEAR_CART = 'CLEAR_CART';
// Products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const GET_PRODUCTS_DETAIL = 'GET_PRODUCTS_DETAIL';
export const FETCH_PRODUCT_DETAILS = 'FETCH_PRODUCT_DETAILS';

// Toast
export const CLOSE_MAX_PRODUCT_MODAL = 'CLOSE_MAX_PRODUCT_MODAL';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
